version: "3.7"
services:

  app:
    image: gonzalovitti/eventapp-backend
    ports: 3000:4000
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: linterna123
      MYSQL_DB: eventapp

  mysql:
    image: mysql:5.7
    volumnes: ./mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: linterna123
      MYSQL_DATABASE: eventapp